name: Portfolio Summary

on:
  schedule:
    - cron: '0 7 * * *'     # 11:00 UTC = 15:00 Dubai time  
  workflow_dispatch:

jobs:
  run-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run all portfolio scripts
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
          GDRIVE_CREDS_JSON:  ${{ secrets.GDRIVE_CREDS_JSON }}
        run: |
          python portfolio-manage/portfolio-positions-manage.py
          python portfolio-manage/send-summary.py
          python portfolio-manage/portfolio-alerts.py
